project_id = "mixie"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

# currently not using realtime
[realtime]
enabled = false


[studio]
enabled = true
port = 54323
api_url = "http://localhost"
openai_api_key = "env(OPENAI_API_KEY)" 

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
port = 54324


# currently not using storage but plan to in the future
[storage]
enabled = false
file_size_limit = "5MB"


[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "http://localhost:54321/auth/v1/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_manual_linking = false

# Email is one of the supported authentication methods
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"



# Google main OAuth provider
[auth.external.google]
enabled = true
client_id="env(GOOGLE_CLIENT_ID)"
secret="env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"


# Will turn on once we have a working mobile application
[auth.external.apple]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_APPLE_SECRET)"
redirect_uri = ""
url = ""


# need this on just incase we have weird issues locally, can disable if needed
[analytics]
enabled = true
port = 54327
vector_port = 54328
backend = "postgres"

