name: "🐛 Bug report"
description: Report an issue or possible bug
title: "[BUG]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## Quick Bug Form
        Thank you for taking the time to file a bug report! Please fill out this form as completely as possible.
- type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      options:
        - Mac
        - Windows
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior, please provide a clear code snippets that always reproduces the issue or a GitHub repository. Screenshots can be provided in the issue body below.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Before posting the issue go through the steps you've written down to make sure the steps provided are detailed and clear.
  - type: markdown
    attributes:
      value: Contributors should be able to follow the steps provided in order to reproduce the bug.
  - type: markdown
    attributes:
      value: Thanks in advance!