name: "💡 Feature request"
description: Suggest new feature for Meally
title: "[FEATURE]: "
labels: ["improvements"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to suggest a new feature idea for Meally! Please fill out this form as completely as possible.
  - type: checkboxes
    attributes:
      label: "Is there an existing feature idea like yours?"
      description: Please search to see if your amazing idea exists or not, if you find a similar one than add to it
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: "Describe the feature you'd like to request"
      description: A clear and concise description of what you want and what your use case is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe the solution you'd like"
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe alternatives you've considered"
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Thank you for your time and consideration! We will get back to you as soon as possible.
