name: Continuous integration

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: 'Install dependencies'
        run: npm install

      - name: 'Run npm ci'
        run: npm ci

      - name: 'Run tests'
        run: npm test

      - name: 'Build'
        run: npm run build
